[package]
name = "bitverter-server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3.0"
maud = { version = "*", features = ["actix-web"] }
tokio = { version = "0.2", features = ["full"] }
reqwest = { version = "0.10", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
